on:
  repository_dispatch: # run manually
    types: [check-link]
  pull_request:
    branches: [ master ]

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
